spring:
  application:
    name: "clinic-organizer"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
logging:
  level:
    root: info
    ru.clinic.org.clinicorganizer: trace
  file:
    name: C:\clinic-organizer\src\main\java\ru\clinic\org\clinicorganizer\logs\clinic-org.log
    path:
      pattern:
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      logback:
        rollingpolicy:
          max-file-size: 10MB
          max-history: 5
          total-size-cap: 50MB